name: deploy-to-azure-environments
concurrency: deploy-mabel


on:
  push:
    branches:
      - main
      - '/release/**'

  workflow_dispatch:
    inputs:
      skipProduction:
        description: 'Skip deploying to production'
        type: boolean
        required: false
        default: true
    
permissions:
  contents: read
  id-token: write

      

  
jobs:        
  ###
  ### Linting (independent of environment)
  ### 
  # lint:
  #   uses: ./.github/workflows/lint.yml
  

  ###
  ### Deploy to the dev environment.
  ###
  deploy-development:
    uses: ./.github/workflows/deploy.yml
    #needs: lint
    with:    
      environmentType: development
      resourceGroupName: mabel-lcms-rg
      
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}



  # Deploy to the production environment.
  # deploy-production:

  #   uses: ./.github/workflows/deploy.yml
  #   needs: deploy-development
  #   with:
  #     environmentType: production
  #     resourceGroupName: mabel-lcms-PROD-rg

  #   secrets:
  #     AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  #     AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  #     AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}


  #     # externalApiKey: <some-key>







  


